openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
tags:
- name: Shipping Calculation
  description: Calculates the carbon footprint for a given flight based on external
    data.
- name: Finance Agreement Calculation
  description: "Calculates finance agreements for car purchases based on valuation,\
    \ credit status, and business margins."
- name: Carbon Footprint Calculation
  description: Calculates the carbon footprint for a given flight based on external
    data.
paths:
  /api/calculateShippingOptions:
    post:
      tags:
      - Shipping Calculation
      summary: Calculate Shipping Options
      description: Calculates the shipping options for a product given external data.
      operationId: calculateShippingOptions
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CalculateShippingOptionsRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CalculateShippingOptionsResponse"
  /api/calculateFinanceAgreement:
    post:
      tags:
      - Finance Agreement Calculation
      summary: Calculate a Finance Agreement
      description: "Processes a finance agreement based on car valuation, customer\
        \ credit profile, business margin constraints, and competitor pricing."
      operationId: calculateFinanceAgreement
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FinanceCalculationRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/FinanceCalculationResponse"
  /api/calculateCarbonFootprint:
    post:
      tags:
      - Carbon Footprint Calculation
      summary: Calculate Carbon Footprint
      description: Calculates the carbon footprint for a given flight based on external
        data.
      operationId: calculateCarbonFootprint
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CarbonFootrintRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CarbonFootprintResponse"
components:
  schemas:
    CalculateShippingOptionsRequest:
      type: object
      properties:
        productId:
          type: string
          description: The Salesforce record ID of the product.
          example: 0035g00000XyZbHAZ
      description: "Request to determine shipping options for a product, including\
        \ the Salesforce record ID of the product being shipped."
    CalculateShippingOptionsResponse:
      type: object
      properties:
        result:
          type: string
      description: Response containing the calculated shipping options for the given
        product.
    FinanceCalculationRequest:
      type: object
      properties:
        customerId:
          type: string
          description: The Salesforce record ID of the customer applying for financing.
          example: 0035g00000XyZbHAZ
        carId:
          type: string
          description: The Salesforce record ID of the car being financed.
          example: a0B5g00000LkVnWEAV
      description: "Request to compute a finance agreement for a car purchase, including\
        \ the Salesforce record ID of both the customer applying for financing and\
        \ the car being financed."
    CarDetails:
      type: object
      properties:
        carId:
          type: string
        make:
          type: string
        model:
          type: string
        year:
          type: integer
          format: int32
        mileage:
          type: integer
          format: int32
        marketValue:
          type: number
          format: double
        tradeInValue:
          type: number
          format: double
      description: Details of the car being financed.
    CounterOffer:
      type: object
      properties:
        adjustedCarPrice:
          type: number
          format: double
        newInterestRate:
          type: number
          format: double
        monthlyPayment:
          type: number
          format: double
        rationale:
          type: string
      description: Counter-offer suggested if the recommended finance offer does not
        meet customer expectations.
    CustomerCreditProfile:
      type: object
      properties:
        creditProfileId:
          type: string
        creditScore:
          type: integer
          format: int32
        loanApprovalStatus:
          type: string
        downPayment:
          type: number
          format: double
        loanTermMonths:
          type: integer
          format: int32
        interestRate:
          type: number
          format: double
      description: Credit profile retrieved for the customer.
    DecisionRationale:
      type: object
      properties:
        pricingStrategy:
          type: string
        customerAffordabilityScore:
          type: integer
          format: int32
        approvalStatus:
          type: string
      description: Rationale for the finance offer decision.
    FinanceCalculationResponse:
      type: object
      properties:
        customerId:
          type: string
        carDetails:
          $ref: "#/components/schemas/CarDetails"
        recommendedFinanceOffer:
          $ref: "#/components/schemas/FinanceOffer"
        profitAnalysis:
          $ref: "#/components/schemas/ProfitAnalysis"
        counterOffer:
          $ref: "#/components/schemas/CounterOffer"
        decisionRationale:
          $ref: "#/components/schemas/DecisionRationale"
        retrievedCustomerCreditProfile:
          $ref: "#/components/schemas/CustomerCreditProfile"
      description: "Response containing the calculated finance agreement, car details,\
        \ profitability analysis, and counter-offer."
    FinanceOffer:
      type: object
      properties:
        finalCarPrice:
          type: number
          format: double
        adjustedInterestRate:
          type: number
          format: double
        monthlyPayment:
          type: number
          format: double
        loanTermMonths:
          type: integer
          format: int32
        totalFinancingCost:
          type: number
          format: double
      description: Recommended finance offer based on business rules and customer
        affordability.
    ProfitAnalysis:
      type: object
      properties:
        profitMargin:
          type: number
          format: double
        meetsMinProfitRequirement:
          type: boolean
      description: Analysis of profit margins based on business constraints.
    CarbonFootrintRequest:
      type: object
      properties:
        flightId:
          type: string
          description: The Salesforce record ID of the flight.
          example: 0035g00000XyZbHAZ
      description: "Request to calculate the carbon footprint of a flight, including\
        \ the Salesforce record ID of the flight being analyzed."
    CarbonFootprintResponse:
      type: object
      properties:
        result:
          type: string
      description: Response containing the calculated carbon footprint for the flight.
